# Database Roles: MIDDLE_EARTH
#
# PURPOSE: Define roles OWNER, WRIUTE & READ for MIDDLE_EATH databse
#
# CHANGELOG -----
# Author:  John Doe
# Date: 9/21/2022
# Description: Created the roles script
#
definitionStyle: snowflake
type: role
spec:
  roles:
    - MIDDLE_EARTH_OWNER
    - MIDDLE_EARTH_READ
    - MIDDLE_EARTH_RW
  grants:
    - role: MIDDLE_EARTH_OWNER
      object:
        type: role
        id: CHANGE_MGMT
    - role: MIDDLE_EARTH_READ
      object:
        type: role
        id: MIDDLE_EARTH_RW
