# Database Roles: MIDDLE_EARTH
#
# PURPOSE: Define roles OWNER, WRIUTE & READ for MIDDLE_EATH databse
#
# CHANGELOG -----
# Author:  John Doe
# Date: 9/21/2022
# Description: Created the roles script
#
definitionStyle: 1.0
type: role
object:
  name: MIDDLE_EARTH
spec:
  pre: |
      CREATE ROLE IF NOT EXISTS MIDDLE_EARTH_OWNER;
      CREATE ROLE IF NOT EXISTS MIDDLE_EARTH_READ;
      CREATE ROLE IF NOT EXISTS MIDDLE_EARTH_WRITE;

      GRANT OWNERSHIP ON ROLE MIDDLE_EARTH_OWNER TO ROLE SYSADMIN;
      GRANT OWNERSHIP ON ROLE MIDDLE_EARTH_READ  TO ROLE SYSADMIN;
      GRANT OWNERSHIP ON ROLE MIDDLE_EARTH_WRITE TO ROLE SYSADMIN;

      GRANT ROLE MIDDLE_EARTH_OWNER TO ROLE SYSADMIN;
      GRANT ROLE MIDDLE_EARTH_READ TO ROLE MIDDLE_EARTH_WRITE;